name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Create DEB package
        run: |
          # Prepare package structure
          mkdir -p deb_build/usr/local/bin
          mkdir -p deb_build/DEBIAN

          cp Invisimark.py deb_build/usr/local/bin/invisimark

          # Create control file
          echo "Package: invisimark" > deb_build/DEBIAN/control
          echo "Version: 1.0" >> deb_build/DEBIAN/control
          echo "Architecture: all" >> deb_build/DEBIAN/control
          echo "Depends: python3, python3-pil" >> deb_build/DEBIAN/control
          echo "Maintainer: Your Name <you@example.com>" >> deb_build/DEBIAN/control
          echo "Description: A Python tool for watermarking images." >> deb_build/DEBIAN/control
          chmod 755 deb_build/usr/local/bin/invisimark

          # Build the .deb package
          dpkg-deb --build deb_build
          mv deb_build.deb invisimark_1.0_all.deb

      - name: Upload DEB package artifact
        uses: actions/upload-artifact@v4
        with:
          name: invisimark-deb-package
          path: invisimark_1.0_all.deb
